<?php


namespace App\Controller;


class News extends Table
{
    protected string $tableName = "news";

    public function actionShowAdd(): void
    {
        parent::actionShowAdd(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("News/add_edit");
    }

    public function actionShowEdit(): void
    {
        parent::actionShowEdit(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("News/add_edit");
    }

    public function actionShow(): void
    {
        parent::actionShow(); // TODO: Change the autogenerated stub
        $this->view->setTemplate("News/show");
    }

    public function actionAdd(): void
    {
//        print_r($_FILES);
        move_uploaded_file(
            $_FILES['picture']['tmp_name'],
            __DIR__ . "/../../public/images/news/" . $_FILES['picture']['name']
        );
        unset($_POST['picture']);
        $this->model->ins($_POST);
        $this->redirect("?type={$this->getCurrentClass()}&action=show");

    }

}